/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity/extract.json
export type Tag = {
  _id: string;
  _type: "tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  color?:
    | "#3B82F6"
    | "#10B981"
    | "#EF4444"
    | "#F59E0B"
    | "#8B5CF6"
    | "#EC4899"
    | "#F97316"
    | "#06B6D4"
    | "#059669"
    | "#6366F1"
    | "#84CC16"
    | "#F43F5E";
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type TagReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "tag";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  body?: Markdown;
  featured_image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  status?: "draft" | "published" | "archived";
  is_featured?: boolean;
  published_at?: string;
  created_at?: string;
  author?: AuthorReference;
  tags?: Array<
    {
      _key: string;
    } & TagReference
  >;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  username?: string;
  slug?: Slug;
  email?: string;
  role?: "admin" | "editor" | "user";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  linkedin_url?: string;
  github_url?: string;
  portfolio_url?: string;
  bio?: Markdown;
  createdAt?: string;
};

export type Markdown = string;

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }
>;

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Tag
  | Slug
  | SanityImageAssetReference
  | AuthorReference
  | TagReference
  | Post
  | Author
  | Markdown
  | SanityImageCrop
  | SanityImageHotspot
  | BlockContent
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/lib/queries.ts
// Variable: allPostsQuery
// Query: *[_type == "post" && status == "published" && select(    defined($tag) => $tag in tags[]->slug.current,    true  )] | order(published_at desc) {  _id,  title,  slug,  excerpt,  featured_image,  status,  is_featured,  published_at,  body,  author-> {    _id,    username,    slug,    image,  },  tags[]-> {    _id,    name,    slug,  },}
export type AllPostsQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  excerpt: string | null;
  featured_image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  status: "archived" | "draft" | "published" | null;
  is_featured: boolean | null;
  published_at: string | null;
  body: Markdown | null;
  author: {
    _id: string;
    username: string | null;
    slug: Slug | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  tags: Array<{
    _id: string;
    name: string | null;
    slug: Slug | null;
  }> | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: postBySlugQuery
// Query: *[_type == "post" && slug.current == $slug && status == "published"][0] {  _id,  title,  slug,  excerpt,  body,  featured_image,  status,  is_featured,  published_at,  author-> {    _id,    username,    slug,    image,},  tags[]-> {    _id,    name,    slug,},}
export type PostBySlugQueryResult = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  excerpt: string | null;
  body: Markdown | null;
  featured_image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  status: "archived" | "draft" | "published" | null;
  is_featured: boolean | null;
  published_at: string | null;
  author: {
    _id: string;
    username: string | null;
    slug: Slug | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  tags: Array<{
    _id: string;
    name: string | null;
    slug: Slug | null;
  }> | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: allTagsQuery
// Query: *[_type == "tag"] | order(name asc) {  _id,  name,  slug,}
export type AllTagsQueryResult = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: relatedPostsQuery
// Query: *[_type == "post" && status == "published" && _id != $currentId && count((tags[]->slug.current)[@ in $tagSlugs]) > 0] | order(published_at desc) [0...$limit] {  _id,  title,  slug,  excerpt,  featured_image,  published_at,  body,  author-> {    _id,    username,    slug,    image,  },  tags[]-> {    _id,    name,    slug,  },}
export type RelatedPostsQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  excerpt: string | null;
  featured_image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  published_at: string | null;
  body: Markdown | null;
  author: {
    _id: string;
    username: string | null;
    slug: Slug | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  tags: Array<{
    _id: string;
    name: string | null;
    slug: Slug | null;
  }> | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "post" && status == "published" && select(\n    defined($tag) => $tag in tags[]->slug.current,\n    true\n  )] | order(published_at desc) {\n  _id,\n  title,\n  slug,\n  excerpt,\n  featured_image,\n  status,\n  is_featured,\n  published_at,\n  body,\n  author-> {\n    _id,\n    username,\n    slug,\n    image,\n  },\n  tags[]-> {\n    _id,\n    name,\n    slug,\n  },\n}': AllPostsQueryResult;
    '*[_type == "post" && slug.current == $slug && status == "published"][0] {\n  _id,\n  title,\n  slug,\n  excerpt,\n  body,\n  featured_image,\n  status,\n  is_featured,\n  published_at,\n  author-> {\n    _id,\n    username,\n    slug,\n    image,\n},\n\n  tags[]-> {\n    _id,\n    name,\n    slug,\n},\n}': PostBySlugQueryResult;
    '*[_type == "tag"] | order(name asc) {\n  _id,\n  name,\n  slug,\n}': AllTagsQueryResult;
  }
}
